version: "3.9"

services:

  booking:
    build: .
    container_name: booking_microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/booking_ms_db
      SPRING_DATASOURCE_USERNAME: booking_ms_db_user
      SPRING_DATASOURCE_PASSWORD: booking_ms_db_password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka_server:9092
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - booking-network

  postgres:
    image: postgres:16-alpine
    container_name: booking-postgres
    environment:
      POSTGRES_DB: booking_ms_db
      POSTGRES_USER: booking_ms_db_user
      POSTGRES_PASSWORD: booking_ms_db_password
    ports:
      - "3001:5432"
    volumes:
      - booking_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booking_ms_db_user -d booking_ms_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - booking-network

  kafka:
    image: confluentinc/cp-kafka:7.7.7
    container_name: kafka_server
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka_server:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - booking-network

volumes:
  booking_db_data:

networks:
  booking-network: